---
title: "NEB_vs_Invitrogen_LbCas12a_comparison.Rmd"
date: "2026-06-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```

## Calculate the Mean normalized fluorescence from the replicates for Invitrogen test
```{r}
rawData = read_delim(file = "Invitrogen_TRBJ1-6_comparison_raw_data.tsv", delim = "\t")


baselineData = rawData %>% 
  filter(Min <=0) %>% 
  select(`CRISPR ID`, Min, Fluorescence) %>% 
  pivot_wider(values_from = Fluorescence, names_from = Min) %>% 
  rowwise() %>%
  mutate(Baseline_mean = mean(c_across(`-10`:`0`))) %>% 
  select(`CRISPR ID`, Baseline_mean)

Fmax = baselineData %>% 
  filter(`CRISPR ID` %in% c("G12_Fmax_2025-11-11")) %>%
  pull(Baseline_mean)

# unicode for delta in R is \u0394, but it turned out I could just insert Δ directly
meannormalizedData_Invitrogen = rawData %>% 
  left_join(baselineData) %>% 
  mutate("Fluorescence Recovery (ΔF%)" = (Fluorescence-Baseline_mean)/(Fmax-Baseline_mean)*100) %>% 
  select(Min,`Donor ID`,Sample_Name,`Sample Type`,`Reaction Conditions`,`crRNA Target`,`Fluorescence Recovery (ΔF%)`, Replicate) %>% 
  pivot_wider(values_from = `Fluorescence Recovery (ΔF%)`,names_from = Replicate) %>% 
  mutate("Mean Fluorescence Recovery (ΔF%)"= rowMeans(across(`1`:`2`))) %>% 
  mutate("notes" = "retest Invitrogen Replicates 1 and 2", "Cas12a" = "Invitrogen")

write_delim(meannormalizedData_Invitrogen, file = "Invitrogen_mean_normalized_data.tsv", delim = "\t")
```

## Compare to Large scale PBMC with NEB Cas12a
```{r}

samples_to_check = c("I05","I07","I08","H02","H06","H08","N04","N05")

# bring in mean normalized data directly, it's calculated in a file that will be available already
meannormalizedData_NEB = read_delim(file = "large_scale_CRISPR_mean_normalized_data.tsv", delim = "\t") %>% 
  filter(`Donor ID` %in% samples_to_check & `crRNA Target` == "TRBJ1-6") %>% 
  rename("1" = "A", "2" = "B") %>% 
  mutate("notes" = "original NEB Replicates 1 and 2", "Cas12a" = "NEB")  # metadata codes the replicates as A and B, I want to switch it to 1 and 2

combined_data_NEB_Invitrogen_test = rbind(meannormalizedData_NEB, meannormalizedData_Invitrogen)

combined_data_NEB_Invitrogen_test$Sample_Name = factor(combined_data_NEB_Invitrogen_test$Sample_Name, levels = c("Healthy PBMC","Non-IBC PBMC","IBC PBMC"))
```

# Figure S5
```{r}
# Figure S5A (breaks function with chatgpt)
combined_data_NEB_Invitrogen_test %>% 
  filter(Min > -1 & `Sample Type` == "PBMC") %>% 
  filter(notes == "retest Invitrogen Replicates 1 and 2" & Min < 65 | notes == "original NEB Replicates 1 and 2") %>%
  ggplot(aes(x = Min, y = `Mean Fluorescence Recovery (ΔF%)`, color = Sample_Name, group = `Donor ID`))+
  geom_line()+
  facet_wrap(Cas12a~`crRNA Target`, scales = "free_x")+
  scale_x_continuous(breaks = function(x) {
    if (max(x) <= 65) c(0, 20, 40, 60)
    else c(0, 60, 120, 180)})+
  theme_bw()+
  scale_color_manual(values = c("#3b3b3b","#4173C6","#FF5733"))+
  theme(legend.position="top")


# Figure S5B
combined_data_NEB_Invitrogen_test %>%
  filter(`Sample Type` == "PBMC") %>% 
  filter(notes == "original NEB Replicates 1 and 2" & Min == 180 | notes == "retest Invitrogen Replicates 1 and 2" & Min == 45) %>%
  ggplot(aes(x = Sample_Name, y = `Mean Fluorescence Recovery (ΔF%)`, color = Sample_Name, shape = Cas12a))+
  geom_boxplot()+
  geom_point(position = position_dodge(width = 0.75))+
  facet_wrap(.~`crRNA Target`)+
  theme_bw()+
  scale_color_manual(values = c("#3b3b3b","#4173C6","#FF5733"))+
  scale_shape_manual(values = c(1,3))+
  ylim(0,100)+
  theme(axis.title.x=element_blank(),legend.position="top")

```


